platform :ios, '9.0'

inhibit_all_warnings!

target 'YUU' do

pod 'AFNetworking'
#pod 'Reachability'
pod 'SDWebImage'
pod 'MJExtension'
pod 'MJRefresh'
#pod 'IQKeyboardManager'
pod 'MBProgressHUD'
pod 'Masonry'
end
